- name: Configure Cisco devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Set login banner
      ios_banner:
        banner: login
        text: "Welcome to {{ inventory_hostname }}!"
        state: present
