- name: Configure Cisco devices
  hosts: all
  gather_facts: no
  vars:
    ansible_user: "{{ lookup('env', 'CISCO_CREDS_USR') }}"
    ansible_password: "{{ lookup('env', 'CISCO_CREDS_PSW') }}"
    ansible_ssh_pass: "{{ ansible_password }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: "{{ ansible_password }}"
    ansible_network_os: ios
    ansible_connection: paramiko
    ansible_command_timeout: 60
    authorize: yes
    auth_pass: "{{ ansible_password }}"
  tasks:
    - name: Check connection type
      debug:
        msg: "Using connection: {{ ansible_connection }}"
    - name: Set login banner
      ios_banner:
        banner: login
        text: |
          Welcome to {{ inventory_hostname }} configured by Ansible
        state: present
