---
- name: Set login banner on all Cisco devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Set login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          Welcome to {{ inventory_hostname }} configured by the Awesome Ansible Applicator
        state: present
